title: "Your Portfolio Title"
description: "Your professional description"
url: "https://yourusername.github.io"
baseurl: "/your-repository-name"  # or "" if using custom domain

author: "Your Name"
twitter:
  username: "yourusername"
social:
  name: "Your Name"
  links:
    - "https://twitter.com/yourusername"
    - "https://linkedin.com/in/yourusername"
    - "https://github.com/yourusername"